[package]
name = "sh-step"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[dependencies]
os_pipe = "0.9"
otto-agent = { path = "../../crates/agent" }
serde = {version = "1", features = ["derive"]}
tempfile = "3"
