[package]
name = "otto-eventbus"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[dependencies]
log = "0.4"
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
