[package]
name = "otto-parser"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[dependencies]
log = "0.4"
otto-models = { path = "../models" }
pest = "2"
pest_derive = "2"
serde_json = "1"
uuid = { version = "0.8", features = ["v4", "serde"]}
