[package]
name = "error-step"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[dependencies]
otto-agent = { path = "../../crates/agent" }
serde = {version = "1", features = ["derive"]}
