#!/usr/bin/env ruby

require 'net/http'
require 'json'
require 'yaml'

data = YAML.load(File.read(ARGV.first))
control = data['control']

if control.nil?
  puts "Did not get a control socket! `error` won't work without it!"
  exit 1
end

# Originally sourced from https://github.com/puppetlabs/net_http_unix under the
# Apache 2.0 License
class HTTPUnix < Net::HTTP
  BufferedIO = ::Net::BufferedIO
  UNIX_REGEXP = %r{^unix://}i

  def initialize(address, port=nil)
    super(address, port)
    case address
    when UNIX_REGEXP
      @socket_type = 'unix'
      @socket_path = address.sub(UNIX_REGEXP, '')
      # Address and port are set to localhost so the HTTP client constructs
      # a HOST request header nginx will accept.
      @address = 'localhost'
      @port = 80
    else
      @socket_type = 'inet'
    end
  end

  def connect
    if @socket_type == 'unix'
      connect_unix
    else
      super
    end
  end

  ##
  # connect_unix is an alternative implementation of Net::HTTP#connect specific
  # to the use case of using a Unix Domain Socket.
  def connect_unix
    D "opening connection to #{@socket_path}..."
    s = Timeout.timeout(@open_timeout) { UNIXSocket.open(@socket_path) }
    D "opened"
    @socket = BufferedIO.new(s)
    @socket.read_timeout = @read_timeout
    @socket.continue_timeout = @continue_timeout
    @socket.debug_output = @debug_output
    on_connect
  end
end

req = Net::HTTP::Post.new('/control', 'Content-Type' => 'application/json')
req.body = {:type => :Terminate}.to_json
client = HTTPUnix.new("unix://#{control}")
client.request(req)
